name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive

      - name: Use Node.js 18.5.0
        uses: actions/setup-node@v2
        with:
          node-version: '18.5.0'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Hexo
        run: npm i hexo-cli -g

      - name: Install Dependencies
        run: npm install

      - name: clean
        run: hexo clean
      
      - name: generate
        run: hexo g

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.HEXO_DEPLOY_KEY }}
      #     publish_dir: ./public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HEXO_DEPLOY_KEY }}
          publish_dir: ./public
          publish_branch: main # default: gh-pages
          external_repository: wrm244/wrm244.github.io # default: ${{ github.repository }}
          cname: wrm244.github.io # optional

      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{secrets.HEXO_DEPLOY_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:wrm244/wrm244.github.io.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:wrm244/wrm244.git"