name: Hexo Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.5.0
      - name: Build and Deploy
        uses: renzhaosy/hexo-deploy-action@master
        env:
          PERSONAL_TOKEN: $ { { secrets.GITHUB_TOKEN }}
          DEPLOY_KEY: $ { { secrets.HEXO_DEPLOY_KEY }}
          PUBLISH_REPOSITORY: wrm244/wrm244.github.io
          BRANCH: main
          PUBLISH_DIR: ./public