name: Hexo Deploy GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: wrm244/hexo-deploy-action@main
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # The repository the action should deploy to.
        SSH_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_KEY }}
        PUBLISH_REPOSITORY: wrm244/wrm244.github.io
        PERSION_NAME: wrm244
        PERSION_MAIL: wrm244@outlook.com

        # The branch the action should deploy to.
        # BRANCH: main